# Generated by Django 3.0.7 on 2021-05-25 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tweeps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweep',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
