# Generated by Django 3.0.7 on 2021-05-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeps', '0002_auto_20210525_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweep',
            name='rating_category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'More than 5 years of tweeting'), (2, 'More than 3.5 years of tweeting'), (3, 'More than 2 years of tweeting'), (4, 'More than 1 year of tweeting'), (5, 'Less than a year of tweeting')], default=5, help_text='For how long have you been tweeting ?'),
        ),
    ]
