# Generated by Django 3.0.7 on 2021-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeps', '0003_tweep_rating_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweep',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
