# Generated by Django 3.0.7 on 2021-05-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeps', '0004_auto_20210525_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweep',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
