# Generated by Django 3.0.7 on 2021-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeps', '0005_auto_20210525_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweep',
            options={'ordering': ['rating_category'], 'verbose_name': 'Tweep KOT', 'verbose_name_plural': 'Tweeps KOT'},
        ),
        migrations.AddField(
            model_name='tweep',
            name='year_born',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AddConstraint(
            model_name='tweep',
            constraint=models.CheckConstraint(check=models.Q(year_born__lte=2003), name='will_be_of_age'),
        ),
    ]
