# Generated by Django 3.0.7 on 2021-05-25 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeps', '0006_auto_20210525_1346'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tweep',
            name='will_be_of_age',
        ),
        migrations.AddField(
            model_name='tweep',
            name='daily_tweet_time',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddConstraint(
            model_name='tweep',
            constraint=models.CheckConstraint(check=models.Q(year_born__lte=2003), name='users_of_age_only'),
        ),
        migrations.AddConstraint(
            model_name='tweep',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_user'),
        ),
    ]
